spring:
    kafka:
      host: localhost
      port: 9092
      consumer:
        group-id: app.1
        auto-offset-reset: earliest
      bootstrap-servers: ${spring.kafka.host}:${spring.kafka.port}
      topic: notify